@startuml

class CreadorDeMazo{

    +crearMazo() : List<Rol>
}

class Partida{
    -jugadores :List<Jugador>
    +iniciar()


}


class ContextoNocturno{
    -unaVotacion : VotacionNocturna
    -unProtegido : Jugador

    +definirProtegido()
    +obtenerBando()
    +getVotacion()
    +getProtegido()
}

class VotacionNocturna{
    -eliminado : Jugador
    -recuentoVotos : Map <Jugador,Int>

    +registrarVoto()
    +obtenerEliminado()


}


class Jugador{
    'elige cualquier rol
    -unRol :Rol

    'la accion depende del rol elegido
    +eleccionNocturna(contexto : ContextoNocturno)
    +elegirObjetivo()
    +eliminar()
    +asignarRol()
    +getRol()
}

interface Rol {
    +eleccionNocturna(contexto : ContextoNocturno)
}

class Padrino{}
class Sheriff{}
class Ciudadano{}

class Medico{
    'elige a quien salvar
    +eleccionNocturna(contexto : ContextoNocturno)
}
class Detective{
    'elige a quien investigar
    +eleccionNocturna(unJugador: Jugadorador,contexto : ContextoNocturno)
}
class Mafioso{
    'elige a quien eliminar
    +eleccionNocturna(unJugador: Jugador,contexto : ContextoNocturno)
}


Jugador --> Rol

Mafioso ..|> Rol
Detective ..|> Rol
Medico ..|> Rol
Padrino ..|> Rol
Sheriff ..|> Rol
Ciudadano ..|> Rol
Partida --> Jugador



@enduml