@startuml


interface ConfiguracionDeMazo{
    +aplicarPara(cantidadJugadores: int) :boolean
    +obtenerCantidadMafiosos() : int
    +agregarRolesEspeciales()

}

class ConfiguracionPequenia{
    -random : Random

    +aplicarPara(cantidadJugadores: int) :boolean
    +obtenerCantidadMafiosos() : int
    +agregarRolesEspeciales()

}

class ConfiguracionMediana{
        -random : Random

        +aplicarPara(cantidadJugadores: int) :boolean
        +obtenerCantidadMafiosos() : int
        +agregarRolesEspeciales()

}

class ConfiguracionGrande{

        +aplicarPara(cantidadJugadores: int) :boolean
        +obtenerCantidadMafiosos() : int
        +agregarRolesEspeciales()

}


class CreadorDeMazo{

    +crearMazo() : List<Rol>
}

class MezcladorDeMazo{
    +mezclar(List<Rol> : mazo)
}

class Partida{
    -jugadores :List<Jugador>
    +iniciar()


}


class ContextoNocturno{
    -unaVotacion : VotacionNocturna
    -unProtegido : Jugador

    +definirProtegido()
    +obtenerBando()
    +getVotacion()
    +getProtegido()
}

class VotacionNocturna{
    -eliminado : Jugador
    -recuentoVotos : Map <Jugador,Int>

    +registrarVoto()
    +obtenerEliminado()


}


class Jugador{
    'elige cualquier rol
    -unRol :Rol

    'la accion depende del rol elegido
    +eleccionNocturna(contexto : ContextoNocturno)
    +elegirObjetivo()
    +eliminar()
    +asignarRol()
    +getRol()
}

interface Rol {
    +eleccionNocturna(contexto : ContextoNocturno)
    +getTipo() : String
}

class Padrino{
    +getTipo() : String
}
class Sheriff{
    +getTipo() : String
}
class Ciudadano{

    +getTipo() : String
}

class Medico{
    'elige a quien salvar
    +eleccionNocturna(contexto : ContextoNocturno)
    +getTipo() : String
}
class Detective{
    'elige a quien investigar
    +eleccionNocturna(unJugador: Jugadorador,contexto : ContextoNocturno)
    +getTipo() : String
}
class Mafioso{
    'elige a quien eliminar
    +eleccionNocturna(unJugador: Jugador,contexto : ContextoNocturno)
    +getTipo() : String
}


Jugador --> Rol

Mafioso ..|> Rol
Detective ..|> Rol
Medico ..|> Rol
Padrino ..|> Rol
Sheriff ..|> Rol
Ciudadano ..|> Rol
Partida --> Jugador

ConfiguracionPequenia ..|> ConfiguracionDeMazo
ConfiguracionMediana ..|> ConfiguracionDeMazo
ConfiguracionGrande ..|> ConfiguracionDeMazo

ConfiguracionDeMazo --> CreadorDeMazo



@enduml